services:
  - type: web
    name: Python-AI-Agents
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chapterGenerator:app --host 0.0.0.0 --port 8001

  - type: web
    name: chatbot-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot_agent:app --host 0.0.0.0 --port 8002

  - type: web
    name: coach-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn coach_agent:app --host 0.0.0.0 --port 8003

  - type: web
    name: quiz-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn quiz_agent:app --host 0.0.0.0 --port 8004
